### ISSUE TITLE
syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by lescheib** [polarvogel/quberspace#1]
Hi beim ausführen bekomme ich den Error : syntax error near unexpected token `newline' 

[$USER@uberspace ~]$ wget https://github.com/polarvogel/quberspace/blob/master/install_qdated.sh
--2018-03-11 13:34:23--  https://github.com/polarvogel/quberspace/blob/master/install_qdated.sh
Resolving github.com... 192.30.253.112, 192.30.253.113
Connecting to github.com|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: `install_qdated.sh'

    [ <=>                                                                                                                ] 53,217       298K/s   in 0.2s

2018-03-11 13:34:24 (298 KB/s) - `install_qdated.sh' saved [53217]

[$USER@uberspace ~]$ chmod +x install_qdated.sh
[$USER@uberspace ~]$ ./install_qdated.sh
./install_qdated.sh: line 7: syntax error near unexpected token `newline'
./install_qdated.sh: line 7: `<!DOCTYPE html>'
[$USER@uberspace ~]$
[$USER@uberspace ~]$

**Comment by polarvogel** [comment]
Hi, schau mal in die Datei, die du heruntergeladen hast: Du hast die Github HTML Seite zu der Datei geladen, brauchst aber die "raw" Datei:

https://raw.githubusercontent.com/polarvogel/quberspace/master/install_qdated.sh

Gruß
